#! /bin/sh
### BEGIN INIT INFO
# Provides:          zabby
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start zabby daemon
### END INIT INFO

set -e

NAME=zabby
DAEMON=/usr/bin/$NAME
RETRY=15

test -x $DAEMON || exit 0

if [ -f /etc/default/zabby ] ; then
    . /etc/default/zabby
fi

if test ! -d "$PID_DIR"; then
  mkdir "$PID_DIR"
  chown -R zabby:zabby "$PID_DIR"
fi


# define LSB log_* functions.
. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $NAME"
    start-stop-daemon --oknodo --start --pidfile $PID_FILE \
      --chuid "$NAME" --exec $DAEMON -- $DAEMON_OPTIONS
    case "$?" in
        0) log_end_msg 0 ;;
        *) log_end_msg 1; exit 1 ;;
    esac
    ;;
  stop)
    log_daemon_msg "Stopping $NAME"
    start-stop-daemon --oknodo --stop --pidfile $PID_FILE --retry $RETRY
    case "$?" in
        0) log_end_msg 0 ;;
        *) log_end_msg 1; exit 1 ;;
    esac
    ;;
  status)
   status_of_proc -p $PID_FILE $DAEMON $NAME && exit 0 || exit $?
   ;;
  reload)
    log_daemon_msg "Reloading $NAME configuration"
    /bin/kill -SIGHUP `cat $PID_FILE`
    log_end_msg 0
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
